_PERFORMANCE_DATA: dict[str, dict] = {
    # =========================================================================
    # 2021
    # =========================================================================
    "the power of the dog": {
        "year": 2021,
        "director": "Jane Campion",
        "director_known_for": "The Piano, Bright Star",
        "cast": "Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": None,
        "budget_usd_m": 39.0,
        "streaming_views_m_first30": 19.0,
        "platform": "Netflix",
        "genre": "Drama/Western",
        "imdb_rating": 6.8,
        "awards": "1 Oscar (Best Director) + 12 Oscar noms",
    },
    "drive my car": {
        "year": 2021,
        "director": "Ryusuke Hamaguchi",
        "director_known_for": "Happy Hour, Wheel of Fortune and Fantasy",
        "cast": "Hidetoshi Nishijima, Toko Miura",
        "opening_week_usd_m": 0.06,
        "box_office_total_usd_m": 1.6,
        "budget_usd_m": None,
        "streaming_views_m_first30": 4.1,
        "platform": "Janus / Mubi",
        "genre": "Drama",
        "imdb_rating": 7.6,
        "awards": "1 Oscar (Best International Film) + 3 Oscar noms",
    },
    "tick tick boom": {
        "year": 2021,
        "director": "Lin-Manuel Miranda",
        "director_known_for": "Hamilton",
        "cast": "Andrew Garfield, Alexandra Shipp, Robin de Jesus",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": None,
        "budget_usd_m": 41.0,
        "streaming_views_m_first30": 13.2,
        "platform": "Netflix",
        "genre": "Drama/Musical",
        "imdb_rating": 7.5,
        "awards": "2 Oscar noms",
    },
    # =========================================================================
    # 2022
    # =========================================================================
    "everything everywhere all at once": {
        "year": 2022,
        "director": "Daniel Kwan, Daniel Scheinert (Daniels)",
        "director_known_for": "Swiss Army Man",
        "cast": "Michelle Yeoh, Ke Huy Quan, Jamie Lee Curtis",
        "opening_week_usd_m": 0.6,
        "box_office_total_usd_m": 69.5,
        "budget_usd_m": 14.3,
        "streaming_views_m_first30": 14.2,
        "platform": "A24 / Prime Video",
        "genre": "Action/Sci-Fi",
        "imdb_rating": 7.8,
        "awards": "7 Oscars",
    },
    "the whale": {
        "year": 2022,
        "director": "Darren Aronofsky",
        "director_known_for": "Black Swan, Requiem for a Dream, The Wrestler",
        "cast": "Brendan Fraser, Sadie Sink, Hong Chau",
        "opening_week_usd_m": 0.2,
        "box_office_total_usd_m": 9.0,
        "budget_usd_m": 8.0,
        "streaming_views_m_first30": 5.1,
        "platform": "A24 / Prime Video",
        "genre": "Drama",
        "imdb_rating": 7.3,
        "awards": "1 Oscar (Best Actor)",
    },
    "tár": {
        "year": 2022,
        "director": "Todd Field",
        "director_known_for": "In the Bedroom, Little Children",
        "cast": "Cate Blanchett, Nina Hoss, Sophie Kauer",
        "opening_week_usd_m": 0.3,
        "box_office_total_usd_m": 35.9,
        "budget_usd_m": 35.0,
        "streaming_views_m_first30": 6.8,
        "platform": "Focus / Peacock",
        "genre": "Drama",
        "imdb_rating": 7.5,
        "awards": "6 Oscar noms",
    },
    "banshees of inisherin": {
        "year": 2022,
        "director": "Martin McDonagh",
        "director_known_for": "Three Billboards, In Bruges",
        "cast": "Colin Farrell, Brendan Gleeson, Kerry Condon",
        "opening_week_usd_m": 0.5,
        "box_office_total_usd_m": 10.6,
        "budget_usd_m": 11.0,
        "streaming_views_m_first30": 8.4,
        "platform": "Searchlight / Hulu",
        "genre": "Drama/Comedy",
        "imdb_rating": 7.7,
        "awards": "9 Oscar noms",
    },
    "all quiet on the western front": {
        "year": 2022,
        "director": "Edward Berger",
        "director_known_for": "Patrick Melrose (series)",
        "cast": "Felix Kammerer, Albrecht Schuch, Daniel Brühl",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": None,
        "budget_usd_m": 20.0,
        "streaming_views_m_first30": 28.0,
        "platform": "Netflix",
        "genre": "War/Drama",
        "imdb_rating": 7.8,
        "awards": "4 Oscars (Best International Film, Cinematography, Score, Production Design)",
    },
    "the menu": {
        "year": 2022,
        "director": "Mark Mylod",
        "director_known_for": "Succession (series), Entourage",
        "cast": "Ralph Fiennes, Anya Taylor-Joy, Nicholas Hoult",
        "opening_week_usd_m": 9.0,
        "box_office_total_usd_m": 38.5,
        "budget_usd_m": 30.0,
        "streaming_views_m_first30": 9.6,
        "platform": "Searchlight / Disney+",
        "genre": "Thriller/Dark Comedy",
        "imdb_rating": 7.2,
        "awards": None,
    },
    "aftersun": {
        "year": 2022,
        "director": "Charlotte Wells",
        "director_known_for": "Debut feature",
        "cast": "Paul Mescal, Frankie Corio",
        "opening_week_usd_m": 0.07,
        "box_office_total_usd_m": 1.6,
        "budget_usd_m": 1.0,
        "streaming_views_m_first30": 3.2,
        "platform": "A24 / Mubi",
        "genre": "Drama",
        "imdb_rating": 7.7,
        "awards": None,
    },
    "glass onion": {
        "year": 2022,
        "director": "Rian Johnson",
        "director_known_for": "Knives Out, Looper, Star Wars: The Last Jedi",
        "cast": "Daniel Craig, Edward Norton, Janelle Monáe, Kate Hudson",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": None,
        "budget_usd_m": 40.0,
        "streaming_views_m_first30": 82.1,
        "platform": "Netflix",
        "genre": "Mystery/Comedy",
        "imdb_rating": 7.1,
        "awards": None,
    },
    "women talking": {
        "year": 2022,
        "director": "Sarah Polley",
        "director_known_for": "Away from Her, Stories We Tell",
        "cast": "Rooney Mara, Claire Foy, Jessie Buckley, Frances McDormand",
        "opening_week_usd_m": 0.05,
        "box_office_total_usd_m": 5.9,
        "budget_usd_m": 11.0,
        "streaming_views_m_first30": 6.2,
        "platform": "United Artists / Prime Video",
        "genre": "Drama",
        "imdb_rating": 7.0,
        "awards": "1 Oscar (Best Adapted Screenplay)",
    },
    # =========================================================================
    # 2023
    # =========================================================================
    "oppenheimer": {
        "year": 2023,
        "director": "Christopher Nolan",
        "director_known_for": "Dunkirk, Interstellar, The Dark Knight, Inception, Tenet",
        "cast": "Cillian Murphy, Emily Blunt, Robert Downey Jr., Matt Damon",
        "opening_week_usd_m": 82.4,
        "box_office_total_usd_m": 952.0,
        "budget_usd_m": 100.0,
        "streaming_views_m_first30": 21.3,
        "platform": "Universal / Peacock",
        "genre": "Biography/Drama",
        "imdb_rating": 8.3,
        "awards": "7 Oscars (Best Picture, Director, Actor, Supporting Actor, Cinematography, Editing, Score)",
    },
    "killers of the flower moon": {
        "year": 2023,
        "director": "Martin Scorsese",
        "director_known_for": "Goodfellas, The Departed, Gangs of New York, Hugo",
        "cast": "Leonardo DiCaprio, Robert De Niro, Lily Gladstone",
        "opening_week_usd_m": 23.0,
        "box_office_total_usd_m": 157.0,
        "budget_usd_m": 200.0,
        "streaming_views_m_first30": 18.5,
        "platform": "Apple TV+",
        "genre": "Crime/Drama",
        "imdb_rating": 7.6,
        "awards": "10 Oscar noms",
    },
    "past lives": {
        "year": 2023,
        "director": "Celine Song",
        "director_known_for": "Debut feature",
        "cast": "Greta Lee, Teo Yoo, John Magaro",
        "opening_week_usd_m": 0.4,
        "box_office_total_usd_m": 10.2,
        "budget_usd_m": 12.0,
        "streaming_views_m_first30": 7.9,
        "platform": "A24 / Showtime",
        "genre": "Drama/Romance",
        "imdb_rating": 7.9,
        "awards": "2 Oscar noms (Best Picture, Best Original Screenplay)",
    },
    "anatomy of a fall": {
        "year": 2023,
        "director": "Justine Triet",
        "director_known_for": "Sibyl, In Bed with Victoria",
        "cast": "Sandra Hüller, Swann Arlaud, Milo Machado Graner",
        "opening_week_usd_m": 0.3,
        "box_office_total_usd_m": 11.8,
        "budget_usd_m": 7.0,
        "streaming_views_m_first30": 5.5,
        "platform": "Neon / Prime Video",
        "genre": "Thriller/Drama",
        "imdb_rating": 7.7,
        "awards": "1 Oscar (Best Original Screenplay) + Palme d'Or Cannes",
    },
    "poor things": {
        "year": 2023,
        "director": "Yorgos Lanthimos",
        "director_known_for": "The Favourite, The Lobster, Dogtooth",
        "cast": "Emma Stone, Mark Ruffalo, Willem Dafoe",
        "opening_week_usd_m": 0.6,
        "box_office_total_usd_m": 35.8,
        "budget_usd_m": 35.0,
        "streaming_views_m_first30": 9.1,
        "platform": "Searchlight / Hulu",
        "genre": "Fantasy/Drama",
        "imdb_rating": 7.9,
        "awards": "4 Oscars (Best Actress, Costume Design, Production Design, Makeup)",
    },
    "zone of interest": {
        "year": 2023,
        "director": "Jonathan Glazer",
        "director_known_for": "Under the Skin, Sexy Beast, Birth",
        "cast": "Christian Friedel, Sandra Hüller",
        "opening_week_usd_m": 0.1,
        "box_office_total_usd_m": 4.2,
        "budget_usd_m": 15.0,
        "streaming_views_m_first30": 3.8,
        "platform": "A24 / Mubi",
        "genre": "Drama/War",
        "imdb_rating": 7.3,
        "awards": "2 Oscars (Best International Film, Best Sound)",
    },
    "the holdovers": {
        "year": 2023,
        "director": "Alexander Payne",
        "director_known_for": "The Descendants, Nebraska, Sideways",
        "cast": "Paul Giamatti, Da'Vine Joy Randolph, Dominic Sessa",
        "opening_week_usd_m": 1.1,
        "box_office_total_usd_m": 18.5,
        "budget_usd_m": 28.0,
        "streaming_views_m_first30": 11.2,
        "platform": "Focus / Peacock",
        "genre": "Drama/Comedy",
        "imdb_rating": 8.0,
        "awards": "1 Oscar (Best Supporting Actress — Da'Vine Joy Randolph)",
    },
    "may december": {
        "year": 2023,
        "director": "Todd Haynes",
        "director_known_for": "Carol, Far From Heaven, I'm Not There",
        "cast": "Natalie Portman, Julianne Moore, Charles Melton",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": None,
        "budget_usd_m": None,
        "streaming_views_m_first30": 8.5,
        "platform": "Netflix",
        "genre": "Drama",
        "imdb_rating": 6.9,
        "awards": "1 Oscar nom (Best Original Screenplay)",
    },
    "the marvels": {
        "year": 2023,
        "director": "Nia DaCosta",
        "director_known_for": "Candyman (2021)",
        "cast": "Brie Larson, Teyonah Parris, Iman Vellani",
        "opening_week_usd_m": 46.1,
        "box_office_total_usd_m": 206.0,
        "budget_usd_m": 220.0,
        "streaming_views_m_first30": 22.5,
        "platform": "Disney / Disney+",
        "genre": "Sci-Fi/Superhero",
        "imdb_rating": 5.5,
        "awards": None,
    },
    "society of the snow": {
        "year": 2023,
        "director": "J.A. Bayona",
        "director_known_for": "A Monster Calls, The Impossible, Jurassic World: Fallen Kingdom",
        "cast": "Enzo Vogrincic, Agustín Pardella, Matías Recalt",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": 7.0,
        "budget_usd_m": 60.0,
        "streaming_views_m_first30": 42.0,
        "platform": "Netflix",
        "genre": "Drama/Survival",
        "imdb_rating": 7.9,
        "awards": "1 Oscar nom (Best International Film)",
    },
    "dream scenario": {
        "year": 2023,
        "director": "Kristoffer Borgli",
        "director_known_for": "Sick of Myself",
        "cast": "Nicolas Cage, Julianne Nicholson, Michael Cera",
        "opening_week_usd_m": 1.4,
        "box_office_total_usd_m": 4.7,
        "budget_usd_m": 10.0,
        "streaming_views_m_first30": 5.8,
        "platform": "A24 / Peacock",
        "genre": "Comedy/Fantasy",
        "imdb_rating": 7.0,
        "awards": None,
    },
    # =========================================================================
    # 2024
    # =========================================================================
    "dune part two": {
        "year": 2024,
        "director": "Denis Villeneuve",
        "director_known_for": "Dune: Part One, Arrival, Blade Runner 2049, Sicario",
        "cast": "Timothée Chalamet, Zendaya, Rebecca Ferguson, Austin Butler",
        "opening_week_usd_m": 82.5,
        "box_office_total_usd_m": 711.8,
        "budget_usd_m": 190.0,
        "streaming_views_m_first30": 35.6,
        "platform": "WB / Max",
        "genre": "Sci-Fi/Adventure",
        "imdb_rating": 8.5,
        "awards": None,
    },
    "conclave": {
        "year": 2024,
        "director": "Edward Berger",
        "director_known_for": "All Quiet on the Western Front (2022)",
        "cast": "Ralph Fiennes, Stanley Tucci, John Lithgow, Isabella Rossellini",
        "opening_week_usd_m": 6.7,
        "box_office_total_usd_m": 43.0,
        "budget_usd_m": 34.0,
        "streaming_views_m_first30": 12.4,
        "platform": "Focus / Prime Video",
        "genre": "Thriller/Drama",
        "imdb_rating": 7.5,
        "awards": "1 Oscar (Best Adapted Screenplay) + 8 Oscar noms",
    },
    "anora": {
        "year": 2024,
        "director": "Sean Baker",
        "director_known_for": "Tangerine, The Florida Project, Red Rocket",
        "cast": "Yura Borisov, Mikey Madison, Aleksei Serebryakov",
        "opening_week_usd_m": 0.5,
        "box_office_total_usd_m": 16.7,
        "budget_usd_m": 6.0,
        "streaming_views_m_first30": 8.3,
        "platform": "Neon / Hulu",
        "genre": "Drama/Romance",
        "imdb_rating": 7.8,
        "awards": "5 Oscars (Best Picture, Director, Actress, Original Screenplay, Editing) + Palme d'Or Cannes",
    },
    "the substance": {
        "year": 2024,
        "director": "Coralie Fargeat",
        "director_known_for": "Revenge (2017)",
        "cast": "Demi Moore, Margaret Qualley, Dennis Quaid",
        "opening_week_usd_m": 0.6,
        "box_office_total_usd_m": 20.5,
        "budget_usd_m": 17.5,
        "streaming_views_m_first30": 12.7,
        "platform": "Mubi",
        "genre": "Horror/Body Horror",
        "imdb_rating": 7.3,
        "awards": "1 Oscar (Best Makeup & Hairstyling) + Cannes Best Screenplay",
    },
    "a real pain": {
        "year": 2024,
        "director": "Jesse Eisenberg",
        "director_known_for": "When You Finish Saving the World",
        "cast": "Jesse Eisenberg, Kieran Culkin",
        "opening_week_usd_m": 0.3,
        "box_office_total_usd_m": 8.5,
        "budget_usd_m": None,
        "streaming_views_m_first30": 6.1,
        "platform": "Searchlight / Hulu",
        "genre": "Drama/Comedy",
        "imdb_rating": 7.8,
        "awards": "1 Oscar (Best Supporting Actor — Kieran Culkin)",
    },
    "emilia perez": {
        "year": 2024,
        "director": "Jacques Audiard",
        "director_known_for": "A Prophet, Rust and Bone, Dheepan",
        "cast": "Karla Sofía Gascón, Zoe Saldaña, Selena Gomez",
        "opening_week_usd_m": None,
        "box_office_total_usd_m": 7.3,
        "budget_usd_m": None,
        "streaming_views_m_first30": 21.0,
        "platform": "Netflix",
        "genre": "Crime/Musical",
        "imdb_rating": 6.6,
        "awards": "2 Oscars (Best Supporting Actress, Best International Film) + 13 Oscar noms",
    },
    "nosferatu": {
        "year": 2024,
        "director": "Robert Eggers",
        "director_known_for": "The Witch, The Lighthouse, The Northman",
        "cast": "Lily-Rose Depp, Bill Skarsgård, Nicholas Hoult, Willem Dafoe",
        "opening_week_usd_m": 21.0,
        "box_office_total_usd_m": 68.0,
        "budget_usd_m": 50.0,
        "streaming_views_m_first30": 11.5,
        "platform": "Focus / Peacock",
        "genre": "Horror",
        "imdb_rating": 7.4,
        "awards": "4 Oscar noms",
    },
    "wicked": {
        "year": 2024,
        "director": "Jon M. Chu",
        "director_known_for": "In the Heights, Crazy Rich Asians",
        "cast": "Cynthia Erivo, Ariana Grande, Jonathan Bailey",
        "opening_week_usd_m": 114.0,
        "box_office_total_usd_m": 735.0,
        "budget_usd_m": 145.0,
        "streaming_views_m_first30": 38.0,
        "platform": "Universal / Peacock",
        "genre": "Musical/Fantasy",
        "imdb_rating": 7.5,
        "awards": "2 Oscar noms",
    },
    "nickel boys": {
        "year": 2024,
        "director": "RaMell Ross",
        "director_known_for": "Hale County This Morning, This Evening (doc)",
        "cast": "Ethan Herisse, Brandon Wilson, Aunjanue Ellis-Taylor",
        "opening_week_usd_m": 0.05,
        "box_office_total_usd_m": 2.1,
        "budget_usd_m": None,
        "streaming_views_m_first30": 4.3,
        "platform": "Amazon MGM / Prime Video",
        "genre": "Drama",
        "imdb_rating": 7.5,
        "awards": "2 Oscar noms (Best Picture, Best Adapted Screenplay)",
    },
    "i saw the tv glow": {
        "year": 2024,
        "director": "Jane Schoenbrun",
        "director_known_for": "We're All Going to the World's Fair",
        "cast": "Justice Smith, Brigette Lundy-Paine",
        "opening_week_usd_m": 0.3,
        "box_office_total_usd_m": 1.5,
        "budget_usd_m": 4.0,
        "streaming_views_m_first30": 3.1,
        "platform": "A24 / Max",
        "genre": "Horror/Drama",
        "imdb_rating": 6.9,
        "awards": None,
    },
    # =========================================================================
    # 2025
    # =========================================================================
    "avatar 3": {
        "year": 2025,
        "director": "James Cameron",
        "director_known_for": "Titanic, Avatar, Terminator 2, Aliens",
        "cast": "Sam Worthington, Zoe Saldaña, Sigourney Weaver",
        "opening_week_usd_m": 104.2,
        "box_office_total_usd_m": None,
        "budget_usd_m": 350.0,
        "streaming_views_m_first30": 48.3,
        "platform": "Disney / Disney+",
        "genre": "Sci-Fi/Action",
        "imdb_rating": None,
        "awards": None,
    },
    "sinners": {
        "year": 2025,
        "director": "Ryan Coogler",
        "director_known_for": "Black Panther, Creed, Fruitvale Station",
        "cast": "Michael B. Jordan, Hailee Steinfeld, Wunmi Mosaku",
        "opening_week_usd_m": 45.0,
        "box_office_total_usd_m": 175.0,
        "budget_usd_m": 90.0,
        "streaming_views_m_first30": None,
        "platform": "WB / Max",
        "genre": "Horror/Drama",
        "imdb_rating": 7.9,
        "awards": None,
    },
    "mickey 17": {
        "year": 2025,
        "director": "Bong Joon-ho",
        "director_known_for": "Parasite, Snowpiercer, Memories of Murder",
        "cast": "Robert Pattinson, Naomi Ackie, Steven Yeun",
        "opening_week_usd_m": 18.4,
        "box_office_total_usd_m": 42.0,
        "budget_usd_m": 118.0,
        "streaming_views_m_first30": None,
        "platform": "WB / Max",
        "genre": "Sci-Fi/Black Comedy",
        "imdb_rating": 6.5,
        "awards": None,
    },
    "mission impossible the final reckoning": {
        "year": 2025,
        "director": "Christopher McQuarrie",
        "director_known_for": "Mission: Impossible — Dead Reckoning, Fallout, Rogue Nation",
        "cast": "Tom Cruise, Hayley Atwell, Simon Pegg, Ving Rhames",
        "opening_week_usd_m": 56.0,
        "box_office_total_usd_m": None,
        "budget_usd_m": 400.0,
        "streaming_views_m_first30": None,
        "platform": "Paramount / Paramount+",
        "genre": "Action/Thriller",
        "imdb_rating": None,
        "awards": None,
    },
}