_PERFORMANCE_DATA: dict[str, dict] = {
    "everything everywhere all at once": {
        "year": 2022,
        "opening_week_usd_m": 0.6,
        "streaming_views_m_first30": 14.2,
        "platform": "A24 / Prime Video",
        "genre": "Action/Sci-Fi",
        "awards": "7 Oscars",
    },
    "the whale": {
        "year": 2022,
        "opening_week_usd_m": 0.2,
        "streaming_views_m_first30": 5.1,
        "platform": "A24 / Prime Video",
        "genre": "Drama",
        "awards": "1 Oscar",
    },
    "tár": {
        "year": 2022,
        "opening_week_usd_m": 0.3,
        "streaming_views_m_first30": 6.8,
        "platform": "Focus / Peacock",
        "genre": "Drama",
        "awards": "6 Oscar noms",
    },
    "banshees of inisherin": {
        "year": 2022,
        "opening_week_usd_m": 0.5,
        "streaming_views_m_first30": 8.4,
        "platform": "Searchlight / Hulu",
        "genre": "Drama",
        "awards": "9 Oscar noms",
    },
    "all quiet on the western front": {
        "year": 2022,
        "opening_week_usd_m": None,
        "streaming_views_m_first30": 28.0,
        "platform": "Netflix",
        "genre": "War/Drama",
        "awards": "4 Oscars",
    },
    "the menu": {
        "year": 2022,
        "opening_week_usd_m": 9.0,
        "streaming_views_m_first30": 9.6,
        "platform": "Searchlight / Disney+",
        "genre": "Thriller",
        "awards": None,
    },
    "aftersun": {
        "year": 2022,
        "opening_week_usd_m": 0.07,
        "streaming_views_m_first30": 3.2,
        "platform": "A24 / Mubi",
        "genre": "Drama",
        "awards": None,
    },
    "glass onion": {
        "year": 2022,
        "opening_week_usd_m": None,
        "streaming_views_m_first30": 82.1,
        "platform": "Netflix",
        "genre": "Mystery",
        "awards": None,
    },
    "oppenheimer": {
        "year": 2023,
        "opening_week_usd_m": 82.4,
        "streaming_views_m_first30": 21.3,
        "platform": "Universal / Peacock",
        "genre": "Biography/Drama",
        "awards": "7 Oscars",
    },
    "killers of the flower moon": {
        "year": 2023,
        "opening_week_usd_m": 23.0,
        "streaming_views_m_first30": 18.5,
        "platform": "Apple TV+",
        "genre": "Crime/Drama",
        "awards": "10 Oscar noms",
    },
    "past lives": {
        "year": 2023,
        "opening_week_usd_m": 0.4,
        "streaming_views_m_first30": 7.9,
        "platform": "A24 / Showtime",
        "genre": "Drama/Romance",
        "awards": "2 Oscar noms",
    },
    "anatomy of a fall": {
        "year": 2023,
        "opening_week_usd_m": 0.3,
        "streaming_views_m_first30": 5.5,
        "platform": "Neon / Prime Video",
        "genre": "Thriller/Drama",
        "awards": "1 Oscar + Palme d'Or",
    },
    "poor things": {
        "year": 2023,
        "opening_week_usd_m": 0.6,
        "streaming_views_m_first30": 9.1,
        "platform": "Searchlight / Hulu",
        "genre": "Fantasy/Drama",
        "awards": "4 Oscars",
    },
    "zone of interest": {
        "year": 2023,
        "opening_week_usd_m": 0.1,
        "streaming_views_m_first30": 3.8,
        "platform": "A24 / Mubi",
        "genre": "Drama/War",
        "awards": "2 Oscars",
    },
    "the holdovers": {
        "year": 2023,
        "opening_week_usd_m": 1.1,
        "streaming_views_m_first30": 11.2,
        "platform": "Focus / Peacock",
        "genre": "Drama/Comedy",
        "awards": "1 Oscar",
    },
    "dune part two": {
        "year": 2024,
        "opening_week_usd_m": 82.5,
        "streaming_views_m_first30": 35.6,
        "platform": "WB / Max",
        "genre": "Sci-Fi/Adventure",
        "awards": None,
    },
    "the marvels": {
        "year": 2023,
        "opening_week_usd_m": 46.1,
        "streaming_views_m_first30": 22.5,
        "platform": "Disney / Disney+",
        "genre": "Sci-Fi/Superhero",
        "awards": None,
    },
    "avatar 3": {
        "year": 2025,
        "opening_week_usd_m": 104.2,
        "streaming_views_m_first30": 48.3,
        "platform": "Disney / Disney+",
        "genre": "Sci-Fi/Action",
        "awards": None,
    },
    "conclave": {
        "year": 2024,
        "opening_week_usd_m": 6.7,
        "streaming_views_m_first30": 12.4,
        "platform": "Focus / Prime Video",
        "genre": "Thriller/Drama",
        "awards": "8 Oscar noms",
    },
    "anora": {
        "year": 2024,
        "opening_week_usd_m": 0.5,
        "streaming_views_m_first30": 8.3,
        "platform": "Neon / Hulu",
        "genre": "Drama/Romance",
        "awards": "5 Oscars + Palme d'Or",
    },
}